spring:
  application:
    name: url-shortener-app

  datasource:
    url: jdbc:mysql://localhost:6969/url-shortener-db
    username: root
    password: rootPASSWORDdocker

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
