spring:
  application:
    name: url-shortener-app

  datasource:
    url: jdbc:mysql://localhost:6969/url-shortener-db
    username: root
    password: rootPASSWORDdocker

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: veryveryveryverylongsecretkeyforjwtgeneration
  expiration: 3600000

logging:
  level:
    org.apache.kafka.clients.consumer: DEBUG
    org.springframework.kafka: DEBUG

